ALTER TABLE Profile MODIFY userId VARCHAR(191) NOT NULL;
ALTER TABLE ConversationParticipant MODIFY userId VARCHAR(191) NOT NULL;
ALTER TABLE Message MODIFY senderId VARCHAR(191) NOT NULL;
ALTER TABLE RandomQueue MODIFY userId VARCHAR(191) NOT NULL;
ALTER TABLE User MODIFY id VARCHAR(191) NOT NULL;
